[build]
command = "unzip -o linkboost_updated.zip && cd linkboost && npm install --legacy-peer-deps && npm run build"
publish = "linkboost/.next"
functions = "linkboost/.netlify/functions"

[build.environment]
NODE_VERSION = "20"
